# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyhabitat"
version = "1.0.32"
#dynamic = ["version"] 
authors = [
  { name="George Clayton Bennett", email="george.bennett@memphistn.gov" },
]
description = "A lightweight library for detecting system environment, GUI, and build properties."
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["environment", "os-detection", "gui", "build-system"]
classifiers=[
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

dependencies = []

[project.scripts]
pyhabitat = "pyhabitat.cli:run_cli"

[tool.setuptools.packages.find]
where = ["."]  
include = ["pyhabitat*"] 

#[project.optional-dependencies]
#typer = ["click", "typer", "rich"]



#[tool.setuptools_scm] 
# This tells setuptools_scm to look at the git history/tags for the version
#write_to = "pyhabitat/_version.py"
